#!/usr/bin/perl
# Writer for implement.pl — builds the engine source programmatically.
use strict; use warnings;

my @L;
sub l { push @L, @_ }

l '#!/usr/bin/perl';
l '# ============================================================================';
l '# implement.pl — Phase 9 Implementation Engine (pine-agent)';
l '# Core Perl 5, zero non-core dependencies. Consumes the authoritative Phase-8';
l '# Implementation Plan and produces generated Pine Script v6 source plus an';
l '# implementation result contract. No semantic drift. No upstream modification.';
l '# No Phase 10. No-Pine output in the result contract (metadata only).';
l '# ============================================================================';
l 'use strict;';
l 'use warnings;';
l 'use Digest::SHA qw(sha256_hex);';
l 'use Encode qw(decode encode);';
l '';
l 'sub _unq { my $s = shift; return undef if !defined $s; $s =~ s/^\x27//; $s =~ s/\x27$//; $s =~ s/\x27\x27/\x27/g; return $s; }';
l '';
l '# Parse the Phase-8 plan YAML (same emit format as implementation_plan.pl).';
l 'sub parse_plan {';
l '    my ($text) = @_;';
l '    die "unparseable: empty plan input\\n" if !defined $text || $text !~ /\\S/;';
l '    my %p;';
l '    my $g = sub { my ($k) = @_; my ($v) = $text =~ /^\\s{2}\\Q$k\\E:\\s*(?:\x27([^\x27]*)\x27|(\\S+))/m; return defined $v ? $v : undef; };';
l '    $p{request_id}           = $g->(\x27request_id\x27);';
l '    $p{approved_routing_id}  = $g->(\x27approved_routing_id\x27);';
l '    $p{formalization_id}     = $g->(\x27formalization_id\x27);';
l '    $p{verification_id}      = $g->(\x27verification_id\x27);';
l '    $p{feasibility_id}       = $g->(\x27feasibility_id\x27);';
l '    $p{planning_id}          = $g->(\x27planning_id\x27);';
l '    $p{planning_status}      = $g->(\x27planning_status\x27);';
l '    my ($ia) = $text =~ /^\\s{2}implementation_allowed:\\s*(true|false)/m;';
l '    $p{implementation_allowed} = (defined $ia && $ia eq \x27true\x27) ? 1 : 0;';
l '    my ($ns) = $text =~ /^\\s{2}next_stage:\\s*(\\S+)/m;';
l '    $p{next_stage} = $ns;';
l '    $p{blockers_empty} = ($text =~ /^  blockers: \\[\\]/m) ? 1 : 0;';
l '    my @mods; my $cap = 0;';
l '    for my $line (split /\\r?\\n/, $text) {';
l '        if ($line =~ /^  modules:\\s*$/) { $cap = 1; next; }';
l '        next unless $cap;';
l '        last if $line =~ /^\\S/ || $line =~ /^  \\w/;';
l '        if ($line =~ /^\\s{4,}-\\s*\\{(.*)\\}\\s*$/) {';
l '            my %m; my $inner = $1;';
l '            while ($inner =~ /\\G\\s*,?\\s*([\\w.]+):\\s*(\x27(?:[^\x27]|\x27\x27)*\x27|[\\w.\\-=]+)/gc) {';
l '                my ($k, $v) = ($1, $2);';
l '                $m{$k} = ($v eq \x27null\x27) ? undef : _unq($v);';
l '            }';
l '            push @mods, \\%m if %m;';
l '        }';
l '    }';
l '    $p{modules} = \\@mods;';
l '    my @sig; $cap = 0;';
l '    for my $line (split /\\r?\\n/, $text) {';
l '        if ($line =~ /^  signal_architecture:\\s*$/) { $cap = 1; next; }';
l '        next unless $cap;';
l '        last if $line =~ /^\\S/ || $line =~ /^  \\w/;';
l '        if ($line =~ /^\\s{4,}-\\s*\\{(.*)\\}\\s*$/) {';
l '            my %s; my $inner = $1;';
l '            while ($inner =~ /\\G\\s*,?\\s*([\\w.]+):\\s*(\x27(?:[^\x27]|\x27\x27)*\x27|[\\w.\\-=]+)/gc) {';
l '                my ($k, $v) = ($1, $2);';
l '                $s{$k} = ($v eq \x27null\x27) ? undef : _unq($v);';
l '            }';
l '            push @sig, \\%s if %s;';
l '        }';
l '    }';
l '    $p{signal_architecture} = \\@sig;';
l '    my @st; $cap = 0;';
l '    for my $line (split /\\r?\\n/, $text) {';
l '        if ($line =~ /^  state_architecture:\\s*$/) { $cap = 1; next; }';
l '        next unless $cap;';
l '        last if $line =~ /^\\S/ || $line =~ /^  \\w/;';
l '        if ($line =~ /^\\s{4,}-\\s*\\{(.*)\\}\\s*$/) {';
l '            my %s; my $inner = $1;';
l '            while ($inner =~ /\\G\\s*,?\\s*([\\w.]+):\\s*(\x27(?:[^\x27]|\x27\x27)*\x27|[\\w.\\-=]+)/gc) {';
l '                my ($k, $v) = ($1, $2);';
l '                $s{$k} = ($v eq \x27null\x27) ? undef : _unq($v);';
l '            }';
l '            push @st, \\%s if %s;';
l '        }';
l '    }';
l '    $p{state_architecture} = \\@st;';
l '    my ($ord) = $text =~ /^\\s{2}implementation_order:\\s*(\\[.*\\])$/m;';
l '    $p{implementation_order} = $ord ? [ ($ord =~ /\x27([^\x27]*)\x27/g) ] : [];';
l '    die "unparseable: no planning block\\n" unless $text =~ /planning/;';
l '    return \\%p;';
l '}';

print join("\n", @L) . "\n";